language: php

php:
    - 7.1.26 # UCRM: 2.14.8
    - 7.2.14 # UCRM: 2.15.0-beta6

branches:
    only:
        - master

install:
    - composer install

#script:
    #- phpunit --bootstrap ./vendor/autoload.php ./tests/UCRM/REST/Endpoints/GeneralTests.php
