language: php

php:
    - 7.1.26    # UCRM: 2.14.8
    - 7.2.14    # UCRM: 2.15.0-beta6

branches:
    only:
        - master

install:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.1.26" ]];   then composer install --no-dev;     fi
    - if [[ "$TRAVIS_PHP_VERSION" == "7.2.14" ]];   then composer install;              fi

deploy:
    provider: releases
    user: $GITHUB_USERNAME
    password: $GITHUB_PASSWORD
    file: "README.md"
    skip_cleanup: true
    draft: true