language: php

php:
    - 7.1.26    # UCRM: 2.14.8
    - 7.2.14    # UCRM: 2.15.0-beta6

branches:
    only:
        - master

install:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.1.26" ]];   then composer install --no-dev;     fi
    - if [[ "$TRAVIS_PHP_VERSION" == "7.2.14" ]];   then composer install;              fi

jobs:
    include:
        - stage: tests-stable
          if: env(TRAVIS_PHP_VERSION) = 7.1.26
          script: "Unit Tests"

        - stage: tests-beta
          if: env(TRAVIS_PHP_VERSION) = 7.2.14
          script: "Unit Tests"

        - stage: release
          name: "GitHub (Draft)"
          install: skip
          script: skip
          deploy:
              provider: releases
              #user: $GITHUB_USERNAME
              #password: $GITHUB_PASSWORD
              api_key: $GITHUB_TOKEN
              #file: "README.md"
              skip_cleanup: true
              draft: true




#deploy:
#    provider: releases
#    #user: $GITHUB_USERNAME
#    #password: $GITHUB_PASSWORD
#    api_key: $GITHUB_TOKEN
#    #file: "README.md"
#    skip_cleanup: true
#    draft: true