language: php

php:
    # UCRM: 2.14.8
    #- 7.1.26
    # UCRM: 2.15.0-beta6
    #- 7.2.14
    # UCRM: 2.15.0
    - 7.2.15

branches:
    only:
        - master

install:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.1.26" ]];   then composer install --no-dev;     fi
    - if [[ "$TRAVIS_PHP_VERSION" == "7.2.14" ]];   then composer install;              fi
    - if [[ "$TRAVIS_PHP_VERSION" == "7.2.15" ]];   then composer install;              fi



jobs:
    include:
        - stage: 2.14.8
          if: env(TRAVIS_PHP_VERSION) = 7.1.26
          script: echo "2.14.8"
        - stage: 2.15.0-beta6
          if: env(TRAVIS_PHP_VERSION) = 7.2.14
          script: echo "2.15.0-beta6"
        - stage: 2.15.0
          if: env(TRAVIS_PHP_VERSION) = 7.2.15
          #name: "UCRM 2.15.0"
          #script: phpunit -v
          script: echo "2.15.0-beta6"

        # Create a Release (Draft) on GitHub
        #- stage: release
        #  install: skip
        #  script: skip
        #  deploy:
        #      provider: releases
        #      api_key: $GITHUB_TOKEN
        #      skip_cleanup: true
        #      draft: true




#deploy:
#    provider: releases
#    #user: $GITHUB_USERNAME
#    #password: $GITHUB_PASSWORD
#    api_key: $GITHUB_TOKEN
#    #file: "README.md"
#    skip_cleanup: true
#    draft: true