language: php

php:
    - 7.1.13
    #- 7.2.14

branches:
    only:
        - master

before_install:
    - composer install

script:
    - phpunit --bootstrap ./vendor/autoload.php ./tests/UCRM/REST/Endpoints/GeneralTests.php
