language: php

php:
    - 7.1.26 # UCRM: 2.14.8
    - 7.2.13 # UCRM: 2.15.0-beta6

branches:
    only:
        - master

matrix:
    include:
        - php: 7.1.26
          env: COMPOSER_ARGS="--no-dev"
        - php: 7.2.13
          env: COMPOSER_ARGS=""

install:
    - composer install $COMPOSER_ARGS

#script:
    #- phpunit --bootstrap ./vendor/autoload.php ./tests/UCRM/REST/Endpoints/GeneralTests.php
