version: 2.1

jobs:
    test_beta:
        docker:
            - image: circleci/php:7.2.15

        environment:
            REST_URL: "https://ucrm.dev.mvqn.net/api/v1.0"

        steps:
            - checkout
            - run: sudo pwd
            - run: sudo composer self-update
            - run: sudo composer install
            - run:
                name: "Environment Variables"
                command: echo 'export REST_URL="$REST_URL"' >> $BASH_ENV
            - run:
                name: "Testing Environment Variables"
                command: echo $REST_URL
            - run:
                name: "Tests"
                command: echo $REST_URL && sudo vendor/bin/phpunit --configuration phpunit.xml




workflows:
    version: 2

    build_and_test:
        jobs:
            - test_beta:
                  context: ucrm.dev.mvqn.net