version: 2

jobs:
    test_beta:
        docker:
            - image: circleci/php:7.2.15
        steps:
            - checkout
            - run: sudo pwd
            - run: sudo composer self-update
            - run: sudo composer install
            - run: sudo find / -name phpunit



workflows:
    version: 2

    build_and_test:
        jobs:
            - test_beta