version: 2

jobs:
    test_beta:
        docker:
            - image: circleci/php:7.2.15

        steps:
            - checkout
            - run:
                name: "Composer Update & Dependency Installation"
                command: |
                    sudo composer self-update
                    sudo composer install
            - run:
                name: "Create File: .env"
                command: |
                    echo "REST_URL=$REST_URL" >> .env
                    echo "REST_KEY=$REST_KEY" >> .env

                    echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
                    echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
                    echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
                    echo "POSTGRES_DB=$POSTGRES_DB" >> .env
                    echo "POSTGRES_USER=$POSTGRES_USER" >> .env

                    echo "HOST_URL=$HOST_URL" >> .env
                    echo "CRYPTO_KEY=$CRYPTO_KEY" >> .env

                    echo "Using the following .env file:"
                    echo ""
                    cat .env
            - run:
                name: "Tests: General"
                command: sudo vendor/bin/phpunit --configuration phpunit.xml --testsuite General
            - run:
                name: "Tests: Client"
                command: sudo vendor/bin/phpunit --configuration phpunit.xml --testsuite Client

            - run:
                name: "Code Coverage"
                command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report

            - store_artifacts:
                  path: build/coverage-report


workflows:
    version: 2

    build_and_test:
        jobs:
            - test_beta:
                  context: ucrm.dev.mvqn.net